### ISSUE TITLE
dist.Matrix.Normal R file 

### ISSUE THREAD

**Issue by phargarten2** [LaplacesDemonR/LaplacesDemon#15]
I recently released a new R package, , matrixNormal, posted on CRAN <see https://cran.r-hub.io/web/packages/matrixNormal/index.html> that has a CDF function has well. The random generation uses Kronecker product of U and V, as well as options to do other decompositions as well. I was finding how matrixNormal was similar or different than others out there. 

The LaplacesDemon::dist.Matrix.Normal Rd file has a density function as well. It uses a logdet function that takes advantage of Cholesky decomposition of positive definite matrices (which I like).  I like this function as it does not seem to impact the random matrix X; X does not need to be positive definite (Iranmanesh et.al. 2010).  The density adds the scale parameters; while the Iranmanesh et.al. 2010 paper subtracts them.
When LaplacesDemon::dmatrixnorm() calculates the density, your code writes as
  `Stuff + logdet(V) * (n/2) + logdet(U) * (k/2))`
But the log of density in Iranmanesh et.al. (2010) is:
 `Stuff - logdet(V) * (n/2) -logdet(U) * (k/2))`
The full code corrected should be:
```{r}
 dens <- -0.5 * tr(as.inverse(V) %*% t(ss) %*% as.inverse(U) %*% 
                      ss) - (log(2 * pi) * (n * k/2) **- logdet(V) * (n/2) -
                               logdet(U) * (k/2))**
```

The other packages and the Wikipedia page (https://en.wikipedia.org/wiki/Matrix_normal_distribution)  do not transpose chol(U), but the rmatrixnorm() function does.
You wrote:
 `X <- M + t(chol(U)) %*% Z %*% chol(V)`
but it should be:
`X <- M + chol(U) %*% Z %*% chol(V) `  

**References**
Iranmanesh, A., Arashi, M., & Tabatabaey, S. M. M. (2010). On Conditional Applications of Matrix Variate Normal Distribution. IJMSI, 5(2), 33–43. https://doi.org/10.7508/ijmsi.2010.02.004

**Comment by phargarten2** [comment]
Edited for clarity and readability.

**Comment by singmann** [comment]
Thanks for the input.
