### ISSUE TITLE
LaplacesDemon.R: Possibility of regularly saving samples

### ISSUE THREAD

**Issue by pglpm** [LaplacesDemonR/LaplacesDemon#20]
Dear all,
It'd be useful if the LaplacesDemon function had the option of saving the value of the "parm" value at regular intervals, more or less as it regularly outputs the value of "LP" (log-probability) for status check. The "parm" values so saved could be used to check how the Monte Carlo sampling is progressing.

It's maybe even better to have the possibility of fully saving the whole sampled values at regular intervals. Otherwise, if the computer crashes, all the samples will be lost. This is costly for Monte Carlo samplings that take days or weeks.

I can try to implement the first or both features in LaplacesDemon.R, if there's enough interest. But afterwards I'd need some help with compilation matters, which are completely opaque to me.

**Comment by singmann** [comment]
Feel free to provide a pull request. I am not actively maintaining the package, so any input needs to come from the community (e.g., you). 

If the pull request looks reasonable and technically acceptable, I am certainly happy to accept it. Ideally with some example code that shows what it does.

**Comment by pglpm** [comment]
Great, thank you! I'll work on that then.
