### ISSUE TITLE
dlnormp

### ISSUE THREAD

**Issue by amawl** [LaplacesDemonR/LaplacesDemon#5]
I am not sure but it seems there is an error in the documentation and also in the code: Should the mu be outside of the log?
curve(dlnormp(x, mu = 5, tau = 1/2), from = 0, to = 10)
This will create NaN for x <= 5 which makes sense if there is a log(x - mu)

**Comment by singmann** [comment]
Are you willing to provide a patch (i.e., pull request)? That would be great.

**Comment by amawl** [comment]
I can try, I have not used github for a while. I will come back to this problem the week-end next week (i.e., 28-29th)

**Comment by singmann** [comment]
Any news on that pull request with the bug fix?

**Comment by amawl** [comment]
My apologise, it was out of my mind... I just forked the this morning. I attached the correction here if you want to check. It should be compatible with the previous version so old code using those function should still work.
I will commit and pull request soon
[testLaplacesDemonCorrection.R.zip](https://github.com/LaplacesDemonR/LaplacesDemon/files/1476131/testLaplacesDemonCorrection.R.zip)

**Comment by amawl** [comment]
I am also going to modify the plot function in another pull request, I would like to add an option to save the pdf on a different name than laplacesDemon.plot.pdf

**Comment by singmann** [comment]
It will be easiest to check the correction on github, once you have committed or submit the pull request. And perhaps it is easiest to submit pull request independently for both issues (i.e., the correction and the pdf issue). But I am very interested in both.

**Comment by singmann** [comment]
Fixed in a419629c15efc2f608f3bf4fd23cab2d203e5520. Thanks a lot!
