### ISSUE TITLE
error in rmatrixnorm

### ISSUE THREAD

**Issue by stla** [LaplacesDemonR/LaplacesDemon#7]
Hello,

 The `rmatrixnorm` function does not correctly sample from a matrix variate normal distribution.

One can see this by checking the expectation of `(X-M)(X-M)'`. This should be equal to `U*tr(V)`. This is not the case:
```
library(LaplacesDemon)
set.seed(314)
U <- rwishart(3, diag(2))
V <- rwishart(3, diag(2))
square <- matrix(0, 2, 2)
for(i in 1:10000){
  X <- rmatrixnorm(matrix(0,2,2), U, V)
  square <- square + X%*%t(X)
}
> square/10000
          [,1]       [,2]
[1,]  2.572725 -1.1191975
[2,] -1.119198  0.7415746
> U*tr(V)
          [,1]      [,2]
[1,]  0.879866 -1.230179
[2,] -1.230179  2.471029
```

The correct sampler is this one:

```
myrmatrixnorm <- function(M, U, V){
  Z <- matrix(rnorm(nrow(M)*ncol(M)), nrow(M), ncol(M))
  M + t(chol(U)) %*% Z %*% chol(V)
}
square <- matrix(0, 2, 2)
for(i in 1:10000){
  X <- myrmatrixnorm(matrix(0,2,2), U, V)
  square <- square + X%*%t(X)
}
> square/10000
           [,1]      [,2]
[1,]  0.8815791 -1.242929
[2,] -1.2429287  2.502462
> U*tr(V)
          [,1]      [,2]
[1,]  0.879866 -1.230179
[2,] -1.230179  2.471029
```

The error is at the last line of `rmatrixnorm`:
`X <- M + chol(U) %*% Z %*% chol(V)`
should be
`X <- M + t(chol(U)) %*% Z %*% chol(V)`

**Comment by singmann** [comment]
Can you provide a pull request with the correction?

**Comment by stla** [comment]
Yes I can. Is it ok if I do a single pull request with several modifications ? (one for each the issues I opened). I don't know how to do separate pull requests.

**Comment by singmann** [comment]
That would be totally fine with me. 
Though it would be great if you still have separate commits per issue, so there is some documentation which change relates to which issue.
