### ISSUE TITLE
improvement of rwishartc and rinvwishart

### ISSUE THREAD

**Issue by stla** [LaplacesDemonR/LaplacesDemon#9]
Hello, 

 Let's take a number of degrees of freedom `nu` and a scale matrix `S`:
```
nu <- 6
p <- 3; S <- cov(matrix(rnorm(10*p),10,p))
```
This is the code of `rwishartc`:
```
k <- nrow(S)
Z <- matrix(0, k, k)
x <- rchisq(k, nu:{
  nu - k + 1
})
x[which(x == 0)] <- 1e-100
diag(Z) <- sqrt(x)
if (k > 1) {
  kseq <- 1:(k - 1)
  Z[rep(k * kseq, kseq) + unlist(lapply(kseq, seq))] <- rnorm(k * 
  {
    k - 1
  }/2)
}
chol(crossprod(Z %*% chol(S)))
```

There's something circular in the final line. In fact, `Z %*% chol(S)` is already the Cholesky factor:

```
> chol(crossprod(Z %*% chol(S)))
         [,1]       [,2]       [,3]
[1,] 4.250561 -0.4035846  0.8737172
[2,] 0.000000  1.4643197 -0.8089389
[3,] 0.000000  0.0000000  1.9047683
> Z %*% chol(S)
         [,1]       [,2]       [,3]
[1,] 4.250561 -0.4035846  0.8737172
[2,] 0.000000  1.4643197 -0.8089389
[3,] 0.000000  0.0000000  1.9047683
```

Thus `rwishartc` would be more efficient by replacing the last line with `Z %*% chol(S)`. 

Also note that the code would be clearer and maybe more efficient by replacing 
`Z[rep(k * kseq, kseq) + unlist(lapply(kseq, seq))] <- `
with 
`Z[upper.tri(Z)] <- `

And one could avoid some repeated code by defining `rwishart` by
```
rwishart <- function(nu, S){
  Z <- rwishartc(nu, S)
  crossprod(Z)
}
```
(currently `rwishart` and `rwishartc` have exactly the same code up to the final line).

Now, once we have an efficient implementation of `rwishartc`, one can improve `rinvwishart`. Currently, `rinvwishart` runs `rwishart` and takes the inverse with `solve`. It is better to get the inverse from the Cholesky factor with the help of `chol2inv`, and then one can define `rinvwishart` like this:

```
rinvwishart <- function(nu, S){
  chol2inv(rwishartc(nu,solve(S)))
}
```

**Comment by singmann** [comment]
Thanks a lot for the comment. Unfortunately, I am not the developer of LaplacesDemon and also do not use it actively. Hence, I cannot really comment on anything related to the use of thee package. I only invested the time to get it back onto CRAN after the original developer disappeared.

So feel free to make this changes and send me a pull request. I will accept them (if the explanation is as reasonable as here and the checks pass). If there are enough bugfixes I will resubmit to CRAN.

So, development on this package is now truly in the hands of the community. So feel free to change what you think is reasonable.
